# Generated by Django 3.1.2 on 2020-11-05 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('cert_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('pass_percent', models.FloatField(max_length=50)),
                ('cost', models.CharField(max_length=500)),
                ('examinee', models.IntegerField(default=0)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='certificate.category')),
            ],
            options={
                'db_table': 'CERTIFICATE',
            },
        ),
        migrations.CreateModel(
            name='CertSchedule',
            fields=[
                # ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_round', models.IntegerField()),
                ('test_type', models.CharField(max_length=10)),
                ('reg_start_date', models.DateField(blank=True, null=True)),
                ('reg_end_date', models.DateField(blank=True, null=True)),
                ('test_start_date', models.DateField(blank=True, null=True)),
                ('test_end_date', models.DateField(blank=True, null=True)),
                ('result_date_1', models.DateField(blank=True, null=True)),
                ('result_date_2', models.DateField(blank=True, null=True)),
                ('cert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate.certificate')),
            ],
            options={
                'db_table': 'CERT_SCHEDULE',
                'unique_together': {('cert_id', 'test_round', 'test_type')},
            },
        ),
    ]
