# Generated by Django 3.1.2 on 2020-11-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyPlan',
        ),
    ]
