# Generated by Django 3.1.2 on 2020-11-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_auto_20201109_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certschedule',
            name='schedule_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
