# Generated by Django 3.1.2 on 2020-11-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0004_remove_certschedule_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
