# Generated by Django 3.1.2 on 2020-11-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_token', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('secret_key', models.CharField(max_length=500)),
                ('interest', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'USER',
            },
        ),
    ]
