# Generated by Django 3.1.2 on 2020-11-05 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('interest', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('cat_likes', models.ManyToManyField(blank=True, to='certificate.Category')),
                ('cert_likes', models.ManyToManyField(blank=True, to='certificate.Certificate')),
            ],
            options={
                'db_table': 'USER',
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('content_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('contents', models.CharField(max_length=1000)),
                ('cert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate.certificate')),
            ],
            options={
                'db_table': 'STUDY_PLAN',
            },
        ),
    ]
