# Generated by Django 3.1.2 on 2020-11-04 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_delete_studyplan'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('content_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('contents', models.CharField(max_length=1000)),
                ('cert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate.certificate')),
                ('id_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'STUDY_PLAN',
            },
        ),
    ]
