# Generated by Django 3.1.2 on 2020-11-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_delete_certschedule'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cat_likes',
            field=models.ManyToManyField(blank=True, related_name='USER_cat_likes', to='certificate.Category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cert_likes',
            field=models.ManyToManyField(blank=True, related_name='USER_cert_likes', to='certificate.Certificate'),
        ),
    ]
