# Generated by Django 3.1.2 on 2020-11-11 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201109_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplan',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plan', to='user.user'),
        ),
    ]
